# -*- coding: utf-8 -*-
"""WiproProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DxAinVL20EfgScyf-_jIRWpiOtDU6rSv
"""

# All Libraries required for this lab are listed below. The libraries pre-installed on Skills Network Labs are commented.
#!pip install pandas==1.3.4
#!pip install scikit-learn==1.0.2
#!pip install numpy==1.21.6

# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

import pandas as pd
from sklearn.linear_model import LinearRegression

# the data set is available at the url below.
URL = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-BD0231EN-SkillsNetwork/datasets/mpg.csv"

# using the read_csv function in the pandas library, we load the data into a dataframe.

df = pd.read_csv(URL)

# show 5 random rows from the dataset
df.sample(5)

df.shape

df.plot.scatter(x = "Horsepower", y = "MPG")

target = df["MPG"]

features = df[["Horsepower","Weight"]]

lr = LinearRegression()

lr.fit(features,target)

#Higher the score, better the model.
lr.score(features,target)

lr.predict([[100,2000]])

import pickle

# Save the trained model to a pickle file
filename = 'linear_regression_model.pkl'
pickle.dump(lr, open(filename, 'wb'))

print(f"Model saved to {filename}")

pip install streamlit==1.36.0

"""Now, let's create a Python file for our Streamlit app. This file will:

1.  Load the `linear_regression_model.pkl` model.
2.  Create input fields for 'Horsepower' and 'Weight'.
3.  Use the model to predict 'MPG' based on the user's input.
4.  Display the predicted 'MPG'.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pickle
# import numpy as np
# 
# st.title('MPG Prediction App')
# 
# # Load the trained model
# filename = 'linear_regression_model.pkl'
# with open(filename, 'rb') as file:
#     model = pickle.load(file)
# 
# st.write("Enter the Horsepower and Weight to predict the MPG.")
# 
# # Input fields for Horsepower and Weight
# horsepower = st.number_input('Horsepower', min_value=1, max_value=300, value=100)
# weight = st.number_input('Weight', min_value=1000, max_value=6000, value=2500)
# 
# # Predict button
# if st.button('Predict MPG'):
#     # Create a numpy array from the inputs
#     input_data = np.array([[horsepower, weight]])
# 
#     # Make prediction
#     prediction = model.predict(input_data)[0]
# 
#     st.success(f'Predicted MPG: {prediction:.2f}')
#

"""To run your Streamlit app, you need to execute the following commands in a new cell. This will launch the Streamlit server and create a public URL for you to access the app."""

!streamlit run app.py & npx localtunnel --port 8501
